# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ghocli < Formula
  desc "Ghost Admin API CLI Tool"
  homepage "https://github.com/mtane0412/ghocli"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mtane0412/ghocli/releases/download/v0.1.0/ghocli_0.1.0_darwin_x86_64.tar.gz"
      sha256 "507b1e899977ec3a783248cccff1ce25cd64461fbbf874146198508700fb449f"

      def install
        bin.install "gho"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mtane0412/ghocli/releases/download/v0.1.0/ghocli_0.1.0_darwin_arm64.tar.gz"
      sha256 "52b22f37efe284b46e5cc80d873b0aa2785f577082eb580f63e9cba5612c96e4"

      def install
        bin.install "gho"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mtane0412/ghocli/releases/download/v0.1.0/ghocli_0.1.0_linux_x86_64.tar.gz"
      sha256 "9fd169bad905f7cf977c358f6a7a50fae3908617c19307354f1ed93777a85d62"
      def install
        bin.install "gho"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mtane0412/ghocli/releases/download/v0.1.0/ghocli_0.1.0_linux_arm64.tar.gz"
      sha256 "863434fd37ab4035ebfa6dfebe93c229f250dc2c165628f64934617580cb1165"
      def install
        bin.install "gho"
      end
    end
  end

  test do
    system "#{bin}/gho", "version"
  end
end
