# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ghocli < Formula
  desc "Ghost Admin API CLI Tool"
  homepage "https://github.com/mtane0412/ghocli"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mtane0412/ghocli/releases/download/v0.1.2/ghocli_0.1.2_darwin_x86_64.tar.gz"
      sha256 "384f25da9f80cfdef99c890c6f26d82236b4c2cf89ebfe78c461eb298579fe2a"

      def install
        bin.install "gho"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mtane0412/ghocli/releases/download/v0.1.2/ghocli_0.1.2_darwin_arm64.tar.gz"
      sha256 "5175900aa17ca4229339c4089e3d1b862386e9dd275697855ae7813b3aefd210"

      def install
        bin.install "gho"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mtane0412/ghocli/releases/download/v0.1.2/ghocli_0.1.2_linux_x86_64.tar.gz"
      sha256 "95d6d0dc62dc216da58d2e116dc775f2490771e75bc976e0c7e7b1e636b264c6"
      def install
        bin.install "gho"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mtane0412/ghocli/releases/download/v0.1.2/ghocli_0.1.2_linux_arm64.tar.gz"
      sha256 "29af7b78a04f5bcc94c44f7ef3ffafa7862975eeb62fad817555f0565f34d57f"
      def install
        bin.install "gho"
      end
    end
  end

  test do
    system "#{bin}/gho", "version"
  end
end
